name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: swift:6.1.2-jammy
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift run carton bundle
    - name: Archive Build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-bundle
        path: ./Bundle
