name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build
      run: carton bundle
    - name: Archive Build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-bundle
        path: ./Bundle
